name: menu-app
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - menu-app-network

  e2e-test-db:
    image: postgres:15.4
    ports:
      - 5435:5432
    env_file:
      - .env.test
    networks:
      - menu-app-network

networks:
  menu-app-network:
