version: '3.8'

name: menu-app
services:
  dev-db:
    image: postgres:15.4
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - menu-app-network
networks:
  menu-app-network:
